// <auto-generated />
using System;
using CharitySystem.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oracle.EntityFrameworkCore.Metadata;

#nullable disable

namespace CharitySystem.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            OracleModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CharitySystem.Domain.Entities.Cloth", b =>
                {
                    b.Property<int>("ClothID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ClothID"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("ClothCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)");

                    b.Property<string>("ClothName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)");

                    b.Property<int>("ClothPoints")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("ClothSize")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("Description")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<int>("IsAvailable")
                        .HasColumnType("NUMBER(10)");

                    b.HasKey("ClothID");

                    b.HasIndex("ClothCode")
                        .IsUnique();

                    b.ToTable("CLOTHES", (string)null);
                });

            modelBuilder.Entity("CharitySystem.Domain.Entities.Family", b =>
                {
                    b.Property<int>("FamilyID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FamilyID"));

                    b.Property<string>("FamilyAddress")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("FamilyCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)");

                    b.Property<string>("FamilyNotes")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<int>("FamilyPoints")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int>("UserID")
                        .HasColumnType("NUMBER(10)");

                    b.HasKey("FamilyID");

                    b.HasIndex("FamilyCode")
                        .IsUnique();

                    b.HasIndex("UserID")
                        .IsUnique();

                    b.ToTable("FAMILIES", (string)null);
                });

            modelBuilder.Entity("CharitySystem.Domain.Entities.FamilyMember", b =>
                {
                    b.Property<int>("MemberID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MemberID"));

                    b.Property<int?>("Age")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int>("FamilyID")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.HasKey("MemberID");

                    b.HasIndex("FamilyID");

                    b.ToTable("FAMILYMEMBERS", (string)null);
                });

            modelBuilder.Entity("CharitySystem.Domain.Entities.Order", b =>
                {
                    b.Property<int>("OrderID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OrderID"));

                    b.Property<int>("FamilyID")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("OrderCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<string>("OrderNotes")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("OrderStatus")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("ShippingAddress")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("NVARCHAR2(250)");

                    b.Property<int>("TotalPoints")
                        .HasColumnType("NUMBER(10)");

                    b.HasKey("OrderID");

                    b.HasIndex("FamilyID");

                    b.ToTable("ORDERS", (string)null);
                });

            modelBuilder.Entity("CharitySystem.Domain.Entities.OrderDetail", b =>
                {
                    b.Property<int>("OrderDetailID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OrderDetailID"));

                    b.Property<int>("ClothID")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int>("OrderID")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int>("Points")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int>("Quantity")
                        .HasColumnType("NUMBER(10)");

                    b.HasKey("OrderDetailID");

                    b.HasIndex("ClothID");

                    b.HasIndex("OrderID");

                    b.ToTable("ORDERDETAILS", (string)null);
                });

            modelBuilder.Entity("CharitySystem.Domain.Entities.User", b =>
                {
                    b.Property<int>("UserID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserID"));

                    b.Property<string>("AccountStatus")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<string>("Fullname")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("NVARCHAR2(20)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)");

                    b.HasKey("UserID");

                    b.HasIndex("PhoneNumber")
                        .IsUnique();

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("USERS", (string)null);
                });

            modelBuilder.Entity("CharitySystem.Domain.Entities.Family", b =>
                {
                    b.HasOne("CharitySystem.Domain.Entities.User", "User")
                        .WithOne()
                        .HasForeignKey("CharitySystem.Domain.Entities.Family", "UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("CharitySystem.Domain.Entities.FamilyMember", b =>
                {
                    b.HasOne("CharitySystem.Domain.Entities.Family", "Family")
                        .WithMany("Members")
                        .HasForeignKey("FamilyID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Family");
                });

            modelBuilder.Entity("CharitySystem.Domain.Entities.Order", b =>
                {
                    b.HasOne("CharitySystem.Domain.Entities.Family", "Family")
                        .WithMany("Orders")
                        .HasForeignKey("FamilyID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Family");
                });

            modelBuilder.Entity("CharitySystem.Domain.Entities.OrderDetail", b =>
                {
                    b.HasOne("CharitySystem.Domain.Entities.Cloth", "Cloth")
                        .WithMany()
                        .HasForeignKey("ClothID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CharitySystem.Domain.Entities.Order", "Order")
                        .WithMany("OrderDetails")
                        .HasForeignKey("OrderID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cloth");

                    b.Navigation("Order");
                });

            modelBuilder.Entity("CharitySystem.Domain.Entities.Family", b =>
                {
                    b.Navigation("Members");

                    b.Navigation("Orders");
                });

            modelBuilder.Entity("CharitySystem.Domain.Entities.Order", b =>
                {
                    b.Navigation("OrderDetails");
                });
#pragma warning restore 612, 618
        }
    }
}
